### ISSUE TITLE
feat: Variational expectations.

### ISSUE THREAD

**Issue by daniel-dodd** [JaxGaussianProcesses/GPJax#101]
# Feature Request

GPJax's SVGP computes variational expectations $\int \text{d} q(f(x_i)) \log( p(y_i|f(x_i))$ via Gauss-Hermite quadrature. 

This is superfluous in cases e.g., of a Gaussian likelihood when the integrand is known is closed form. It would be beneficial to override this automatically.

Additionally, it would nice to offer alternatives such as Monte Carlo.

**Comment by Daniel-Dodd** [comment]
Questions:

1. When the integrand is known in closed form, where should we put it?
2. Could we define the integration strategy when initialising `StochasticVI`?

**Comment by Daniel-Dodd** [comment]
@thomaspinder Resolving the Gaussian case for the analytical variational expectation, would allow us to test the collapsed bound agrees with Natural gradients after one gradient update with fixed hyper-parameters (#90). Currently, both bounds almost agree, but differ due to the quadrate approximation.

**Comment by thomaspinder** [comment]
Closing in lieu of #270
