### ISSUE TITLE
dev: Flag when the PyTree is in its constrained or unconstrained state

### ISSUE THREAD

**Issue by thomaspinder** [JaxGaussianProcesses/GPJax#274]
There is currently nothing preventing someone calling `constrain` on the PyTree, and then calling `constrain` again. This is problematic as, for a log-exp biejctor, you would essentially be setting the parameter value to $\exp(\exp(x))$. 

We can solve this by having a boolean flag on the PyTree that indicates whether or note the tree is in its constrained state. When calling `unconstrain` a new PyTree is returned where the flag will be set to False. Calling constrain when the flag is True (i.e., the tree is in its constrained state) should throw a warning and just return the original tree. However, users should be able to override this behaviour by calling `.constrain(force=True)`.

**Comment by frazane** [comment]
So I started looking into this and my current solution is to add a boolean flag `constrained` as a `static_field`, defined in https://github.com/JaxGaussianProcesses/GPJax/blob/6408c68beec68f0f6839d27c111c311a10e11228/gpjax/base/module.py#L93 so that all subclasses of `Module` automatically have this flag, and it can be replaced with e.g.  `.replace(constrained=False)`  inside the call `.unconstrain()`. 

The issue now is that the `PytreeDef`, returned by `jax.tree_util.tree_structure`, is not the same if static arguments change (`True != False`). So for example this assertion fails: 

https://github.com/JaxGaussianProcesses/GPJax/blob/6408c68beec68f0f6839d27c111c311a10e11228/tests/test_base/test_module.py#L467

@daniel-dodd how much of a problem is this? Should we look into an alternative solution? 

Also, we should think of how this issue relates to https://github.com/JaxGaussianProcesses/GPJax/issues/287 since we will need a recursive logic here as well.

**Comment by daniel-dodd** [comment]
Nice stuff @frazane! This is the solution I would have gone for, however will mean slower/additional compilation.

One alternative would be to use a global state and a context manager, similar to treeo's `_MutableContext` https://github.com/cgarciae/treeo/blob/b77bbfaf392a655c914b95a4d2dec6b9df9baf57/treeo/tree.py#LL145C7-L145C22 . 

This is more complex, but would alleviate this.
