### ISSUE TITLE
bug: NotImplementedError when fitting Sparse GP

### ISSUE THREAD

**Issue by AhmadAmine998** [JaxGaussianProcesses/GPJax#479]
# Bug Report

**GPJax version:**
0.9.2
**Current behavior:**

When trying to run the stochastic [sparse GP example](https://docs.jaxgaussianprocesses.com/_examples/collapsed_vi/#dataset) with CUDA-enabled JAX, I get the following error:
`host_callback functionality isn't supported with PJRT C API. See https://jax.readthedocs.io/en/latest/debugging/index.html and https://jax.readthedocs.io/en/latest/notebooks/external_callbacks.html for alternatives.

Which is triggered by the line:
`opt_posterior, history = gpx.fit(
    model=q,
    # we want want to minimize the *negative* ELBO
    objective=lambda p, d: -gpx.objectives.collapsed_elbo(p, d),
    train_data=D,
    optim=ox.adamw(learning_rate=1e-2),
    num_iters=500,
    key=key,
)`

**Expected behavior:**

The GP trains.

**Steps to reproduce:**

1. Create a new virtualenv `virtualenv gpJax_env`
2. Activate the virtualenv `gpJax_env/bin/activate`
3. Install gp JAX using `pip install gpjax`
4. Install CUDA-enabled jax as [per the installation guide](https://github.com/jax-ml/jax#installation) using `pip install -U "jax[cuda12]"`
5. Run the stochastic [sparse GP example ](https://github.com/JaxGaussianProcesses/GPJax/blob/main/examples/uncollapsed_vi.py)

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by stefanocortinovis** [comment]
Hi @AhmadAmine998! I think this might be due to the deprecation of `jax.experimental.host_callback()` in favour of `jax.debug.callback()` (see [here](https://github.com/jax-ml/jax/issues/20385)).

Could you check if the changes I made in [this fork](https://github.com/stefanocortinovis/GPJax) solve the issue? Alternatively, calling `fit()` with `verbose=False` could be another temporary fix.
